steps:
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args: ['-c', 'docker pull us-central1-docker.pkg.dev/civil-zodiac-422613-b7/cloud-run-source-deploy/test_1:latest || exit 0']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--cache-from', 'us-central1-docker.pkg.dev/civil-zodiac-422613-b7/cloud-run-source-deploy/test_1:latest', '-t', 'us-central1-docker.pkg.dev/civil-zodiac-422613-b7/cloud-run-source-deploy/test_1:latest', '.']
images: ['us-central1-docker.pkg.dev/civil-zodiac-422613-b7/cloud-run-source-deploy/test_1:latest']